org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon=true
android.useAndroidX=true
appVersionName=3.0.2
appVersionCode=2026083002

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
